package uk.gov.moj.cp.retrieval.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.anyString;
import static org.mockito.Mockito.eq;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static uk.gov.moj.cp.retrieval.service.ResponseGenerationService.SYSTEM_PROMPT_TEMPLATE;

import uk.gov.moj.cp.ai.exception.ChatServiceException;
import uk.gov.moj.cp.ai.model.ChunkedEntry;
import uk.gov.moj.cp.ai.service.ChatService;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

class ResponseGenerationServiceTest {

    @Mock
    private ChatService mockChatService;

    @Mock
    private CitationProcessor citationProcessor;

    @Mock
    private ChunkFormatterService chunkFormatterService;

    @Mock
    private UserInstructionService userInstructionService;

    private ResponseGenerationService responseGenerationService;

    final String mockProcessedResponse = "Some random processed response";
    final String mockFormattedChunk = "Some random formatted chunk entry";
    final String mockUserInstructions = "Some random generated user instructions";

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
        responseGenerationService = new ResponseGenerationService(mockChatService, citationProcessor, chunkFormatterService, userInstructionService);
    }

    @Test
    void generateResponse_ReturnsTrimmedAndCitationFormattedResponse_WhenChatServiceReturnsValidResponse() throws ChatServiceException {
        final String userQuery = "What is the legal implication?";
        final String userQueryPrompt = "Provide detailed legal advice.";

        List<ChunkedEntry> chunkedEntries = new ArrayList<>();
        chunkedEntries.add(ChunkedEntry.builder()
                .id("id1")
                .chunk("Chunk 1")
                .documentFileName("file name 1")
                .pageNumber(1)
                .documentId("2876")
                .build());


        String mockResponse = "Valid AI Response [1]] " +
                "and even more response with faulty citation [2]";

        when(citationProcessor.processAndFormatCitations(mockResponse)).thenReturn(mockProcessedResponse);
        when(chunkFormatterService.buildChunkContext(chunkedEntries)).thenReturn(mockFormattedChunk);
        when(userInstructionService.buildUserInstruction(userQuery, userQueryPrompt, mockFormattedChunk)).thenReturn(mockUserInstructions);
        when(mockChatService.callModel(eq(SYSTEM_PROMPT_TEMPLATE), eq(mockUserInstructions), eq(String.class)))
                .thenReturn(Optional.of(mockResponse));

        String result = responseGenerationService.generateResponse(userQuery, chunkedEntries, userQueryPrompt);

        assertEquals(mockProcessedResponse, result);
        verify(citationProcessor).processAndFormatCitations(mockResponse);
        verify(chunkFormatterService).buildChunkContext(chunkedEntries);
        verify(userInstructionService).buildUserInstruction(userQuery, userQueryPrompt, mockFormattedChunk);
        verify(mockChatService).callModel(eq(SYSTEM_PROMPT_TEMPLATE), eq(mockUserInstructions), eq(String.class));
    }

    @Test
    void generateResponse_ReturnsNoResponseMessage_WhenChatServiceReturnsEmpty() throws ChatServiceException {
        String userQuery = "What is the legal implication?";
        String userQueryPrompt = "Provide detailed legal advice.";
        List<ChunkedEntry> chunkedEntries = List.of(
                ChunkedEntry.builder()
                        .id("id1")
                        .chunk("Chunk 1")
                        .documentFileName("file name 1")
                        .pageNumber(1)
                        .documentId("doc id")
                        .build()
        );

        when(chunkFormatterService.buildChunkContext(chunkedEntries)).thenReturn(mockFormattedChunk);
        when(userInstructionService.buildUserInstruction(userQuery, userQueryPrompt, mockFormattedChunk)).thenReturn(mockUserInstructions);
        when(mockChatService.callModel(eq(SYSTEM_PROMPT_TEMPLATE), eq(mockUserInstructions), eq(String.class)))
                .thenReturn(Optional.empty());

        String result = responseGenerationService.generateResponse(userQuery, chunkedEntries, userQueryPrompt);

        assertEquals("No response generated by the service.", result);

        verify(mockChatService).callModel(eq(SYSTEM_PROMPT_TEMPLATE), eq(mockUserInstructions), eq(String.class));
        verify(citationProcessor, never()).processAndFormatCitations(any());
        verify(chunkFormatterService).buildChunkContext(chunkedEntries);
        verify(userInstructionService).buildUserInstruction(userQuery, userQueryPrompt, mockFormattedChunk);
    }

    @Test
    void generateResponse_ReturnsErrorMessage_WhenChatServiceThrowsException() throws ChatServiceException {
        String userQuery = "What is the legal implication?";
        String userQueryPrompt = "Provide detailed legal advice.";
        List<ChunkedEntry> chunkedEntries = List.of(
                ChunkedEntry.builder()
                        .id("id1")
                        .chunk("Chunk 1")
                        .documentFileName("file name 1")
                        .pageNumber(1)
                        .documentId("doc id")
                        .build()
        );

        when(chunkFormatterService.buildChunkContext(chunkedEntries)).thenReturn(mockFormattedChunk);
        when(userInstructionService.buildUserInstruction(userQuery, userQueryPrompt, mockFormattedChunk)).thenReturn(mockUserInstructions);
        when(mockChatService.callModel(eq(SYSTEM_PROMPT_TEMPLATE), eq(mockUserInstructions), eq(String.class)))
                .thenThrow(new RuntimeException("Service error"));

        String result = responseGenerationService.generateResponse(userQuery, chunkedEntries, userQueryPrompt);

        assertEquals("An error occurred while generating the response.", result);
        verify(mockChatService).callModel(eq(SYSTEM_PROMPT_TEMPLATE), eq(mockUserInstructions), eq(String.class));
        verify(citationProcessor, never()).processAndFormatCitations(any());
        verify(chunkFormatterService).buildChunkContext(chunkedEntries);
        verify(userInstructionService).buildUserInstruction(userQuery, userQueryPrompt, mockFormattedChunk);
    }

    @Test
    void generateResponse_ReturnsDefaultContextMessage_WhenChunkedEntriesAreNullOrEmpty() throws ChatServiceException {
        final String userQuery = "What is the legal implication?";
        final String userQueryPrompt = "Provide detailed legal advice.";
        final String sampleResponse = "No response generated by the service.";

        String resultWithNullEntries = responseGenerationService.generateResponse(userQuery, null, userQueryPrompt);
        assertEquals(sampleResponse, resultWithNullEntries);

        String resultWithEmptyEntries = responseGenerationService.generateResponse(userQuery, List.of(), userQueryPrompt);
        assertEquals(sampleResponse, resultWithEmptyEntries);

        verify(mockChatService, never()).callModel(anyString(), eq(userQuery), eq(String.class));
    }
}
