package uk.gov.moj.cp.retrieval.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.anyString;
import static org.mockito.Mockito.eq;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import uk.gov.moj.cp.ai.exception.ChatServiceException;
import uk.gov.moj.cp.ai.model.ChunkedEntry;
import uk.gov.moj.cp.ai.service.ChatService;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

class ResponseGenerationServiceTest {

    @Mock
    private ChatService mockChatService;

    private ResponseGenerationService responseGenerationService;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
        responseGenerationService = new ResponseGenerationService(mockChatService);
    }

    @Test
    void generateResponse_ReturnsTrimmedAndCitationFormattedResponse_WhenChatServiceReturnsValidResponse() throws ChatServiceException {
        String userQuery = "What is the legal implication?";
        String userQueryPrompt = "Provide detailed legal advice.";
        List<ChunkedEntry> chunkedEntries = new ArrayList<>();
        chunkedEntries.add(ChunkedEntry.builder()
                .id("id1")
                .chunk("Chunk 1")
                .documentFileName("file name 1")
                .pageNumber(1)
                .documentId("2876")
                .build());
        chunkedEntries.add(ChunkedEntry.builder()
                .id("id2")
                .chunk("Chunk 2")
                .documentFileName("file name 2")
                .pageNumber(2)
                .documentId("2876")
                .build());
        String mockResponse = "Valid AI Response (Source: [Possess Blade IDPC.pdf], Pages 10-12,14,20|10,11,12,14,20|documentId=2876) " +
                "and more response with faulty citation (Sources: [Possess Blade IDPC1.pdf], Pages 10-12,14,20|10,11,12,14,20|documentId=2876]) " +
                "and even more response with faulty citation (source: [Possess Blade IDPC2.pdf], Pages 10-12,14,20|10,11,12,14,20|documentId=2876]) " +
                "and even more response with faulty citation (sources: [Possess Blade IDPC3.pdf], Pages 10-12,14,20|10,11,12,14,20|documentId=2876])";

        String formattedValidResponse = "Valid AI Response ::(Source: [Possess Blade IDPC.pdf], Pages 10-12,14,20|10,11,12,14,20|documentId=2876) " +
                "and more response with faulty citation ::(Source: [Possess Blade IDPC1.pdf], Pages 10-12,14,20|10,11,12,14,20|documentId=2876) " +
                "and even more response with faulty citation ::(Source: [Possess Blade IDPC2.pdf], Pages 10-12,14,20|10,11,12,14,20|documentId=2876) " +
                "and even more response with faulty citation ::(Source: [Possess Blade IDPC3.pdf], Pages 10-12,14,20|10,11,12,14,20|documentId=2876)";

        when(mockChatService.callModel(anyString(), eq(userQuery), eq(String.class)))
                .thenReturn(Optional.of(mockResponse));

        String result = responseGenerationService.generateResponse(userQuery, chunkedEntries, userQueryPrompt);

        assertEquals(formattedValidResponse, result);
        verify(mockChatService).callModel(anyString(), eq(userQuery), eq(String.class));
    }

    @Test
    void generateResponse_ReturnsNoResponseMessage_WhenChatServiceReturnsEmpty() throws ChatServiceException {
        String userQuery = "What is the legal implication?";
        String userQueryPrompt = "Provide detailed legal advice.";
        List<ChunkedEntry> chunkedEntries = List.of(
                ChunkedEntry.builder()
                        .id("id1")
                        .chunk("Chunk 1")
                        .documentFileName("file name 1")
                        .pageNumber(1)
                        .documentId("doc id")
                        .build()
        );

        when(mockChatService.callModel(anyString(), eq(userQuery), eq(String.class)))
                .thenReturn(Optional.empty());

        String result = responseGenerationService.generateResponse(userQuery, chunkedEntries, userQueryPrompt);

        assertEquals("No response generated by the service.", result);
        verify(mockChatService).callModel(anyString(), eq(userQuery), eq(String.class));
    }

    @Test
    void generateResponse_ReturnsErrorMessage_WhenChatServiceThrowsException() throws ChatServiceException {
        String userQuery = "What is the legal implication?";
        String userQueryPrompt = "Provide detailed legal advice.";
        List<ChunkedEntry> chunkedEntries = List.of(
                ChunkedEntry.builder()
                        .id("id1")
                        .chunk("Chunk 1")
                        .documentFileName("file name 1")
                        .pageNumber(1)
                        .documentId("doc id")
                        .build()
        );

        when(mockChatService.callModel(anyString(), eq(userQuery), eq(String.class)))
                .thenThrow(new RuntimeException("Service error"));

        String result = responseGenerationService.generateResponse(userQuery, chunkedEntries, userQueryPrompt);

        assertEquals("An error occurred while generating the response.", result);
        verify(mockChatService).callModel(anyString(), eq(userQuery), eq(String.class));
    }

    @Test
    void generateResponse_ReturnsDefaultContextMessage_WhenChunkedEntriesAreNullOrEmpty() throws ChatServiceException {
        String userQuery = "What is the legal implication?";
        String userQueryPrompt = "Provide detailed legal advice.";

        when(mockChatService.callModel(anyString(), eq(userQuery), eq(String.class)))
                .thenReturn(Optional.of("Valid AI Response"));

        String resultWithNullEntries = responseGenerationService.generateResponse(userQuery, null, userQueryPrompt);
        assertEquals("Valid AI Response", resultWithNullEntries);
        verify(mockChatService).callModel(anyString(), eq(userQuery), eq(String.class));

        String resultWithEmptyEntries = responseGenerationService.generateResponse(userQuery, List.of(), userQueryPrompt);
        assertEquals("Valid AI Response", resultWithEmptyEntries);
        verify(mockChatService, times(2)).callModel(anyString(), eq(userQuery), eq(String.class));
    }
}
