package uk.gov.moj.cp.ai;

public class SharedSystemVariables {

    public static final String AI_RAG_SERVICE_STORAGE_ACCOUNT_CONNECTION_MODE = "AI_RAG_SERVICE_STORAGE_ACCOUNT_CONNECTION_MODE";
    public static final String AI_RAG_SERVICE_STORAGE_ACCOUNT_CONNECTION_STRING = "AI_RAG_SERVICE_STORAGE_ACCOUNT_CONNECTION_STRING";
    public static final String AI_RAG_SERVICE_STORAGE_ACCOUNT_NAME = "AI_RAG_SERVICE_STORAGE_ACCOUNT_NAME";
    public static final String AI_RAG_SERVICE_BLOB_STORAGE_ENDPOINT = "AI_RAG_SERVICE_BLOB_STORAGE_ENDPOINT";
    public static final String AI_RAG_SERVICE_TABLE_STORAGE_ENDPOINT = "AI_RAG_SERVICE_TABLE_STORAGE_ENDPOINT";
    public static final String AI_RAG_SERVICE_QUEUE_STORAGE_ENDPOINT = "AI_RAG_SERVICE_QUEUE_STORAGE_ENDPOINT";

    public static final String STORAGE_ACCOUNT_QUEUE_ANSWER_SCORING = "STORAGE_ACCOUNT_QUEUE_ANSWER_SCORING";
    public static final String STORAGE_ACCOUNT_QUEUE_DOCUMENT_INGESTION = "STORAGE_ACCOUNT_QUEUE_DOCUMENT_INGESTION";

    public static final String STORAGE_ACCOUNT_TABLE_DOCUMENT_INGESTION_OUTCOME = "STORAGE_ACCOUNT_TABLE_DOCUMENT_INGESTION_OUTCOME";

    public static final String STORAGE_ACCOUNT_BLOB_CONTAINER_NAME = "STORAGE_ACCOUNT_BLOB_CONTAINER_NAME";
    public static final String STORAGE_ACCOUNT_BLOB_CONTAINER_NAME_EVAL_PAYLOADS = "STORAGE_ACCOUNT_BLOB_CONTAINER_NAME_EVAL_PAYLOADS";

    public static final String AZURE_EMBEDDING_SERVICE_ENDPOINT = "AZURE_EMBEDDING_SERVICE_ENDPOINT";
    public static final String AZURE_EMBEDDING_SERVICE_DEPLOYMENT_NAME = "AZURE_EMBEDDING_SERVICE_DEPLOYMENT_NAME";

    public static final String AZURE_SEARCH_SERVICE_ENDPOINT = "AZURE_SEARCH_SERVICE_ENDPOINT";
    public static final String AZURE_SEARCH_SERVICE_INDEX_NAME = "AZURE_SEARCH_SERVICE_INDEX_NAME";

    private SharedSystemVariables() {
        // Prevent instantiation
    }


}
