package uk.gov.moj.cp.ai;

public class SharedSystemVariables {

    // Identity-based binding prefix for the Functions storage triggers/outputs.
    // The Functions host resolves the matching `__accountName` app setting and authenticates via managed identity.
    public static final String AI_RAG_SERVICE_STORAGE_ACCOUNT_CONNECTION_STRING = "AI_RAG_SERVICE_STORAGE_ACCOUNT_CONNECTION_STRING";
    public static final String AI_RAG_SERVICE_BLOB_STORAGE_ENDPOINT = "AI_RAG_SERVICE_BLOB_STORAGE_ENDPOINT";
    public static final String AI_RAG_SERVICE_TABLE_STORAGE_ENDPOINT = "AI_RAG_SERVICE_TABLE_STORAGE_ENDPOINT";

    public static final String STORAGE_ACCOUNT_QUEUE_ANSWER_SCORING = "STORAGE_ACCOUNT_QUEUE_ANSWER_SCORING";
    public static final String STORAGE_ACCOUNT_QUEUE_ANSWER_GENERATION = "STORAGE_ACCOUNT_QUEUE_ANSWER_GENERATION";

    public static final String STORAGE_ACCOUNT_QUEUE_DOCUMENT_INGESTION = "STORAGE_ACCOUNT_QUEUE_DOCUMENT_INGESTION";

    public static final String STORAGE_ACCOUNT_TABLE_ANSWER_GENERATION = "STORAGE_ACCOUNT_TABLE_ANSWER_GENERATION";
    public static final String STORAGE_ACCOUNT_TABLE_DOCUMENT_INGESTION_OUTCOME = "STORAGE_ACCOUNT_TABLE_DOCUMENT_INGESTION_OUTCOME";

    public static final String STORAGE_ACCOUNT_BLOB_CONTAINER_NAME_DOCUMENT_UPLOAD = "STORAGE_ACCOUNT_BLOB_CONTAINER_NAME_DOCUMENT_UPLOAD";
    public static final String STORAGE_ACCOUNT_BLOB_CONTAINER_NAME_EVAL_PAYLOADS = "STORAGE_ACCOUNT_BLOB_CONTAINER_NAME_EVAL_PAYLOADS";
    public static final String STORAGE_ACCOUNT_BLOB_CONTAINER_NAME_INPUT_CHUNKS = "STORAGE_ACCOUNT_BLOB_CONTAINER_NAME_INPUT_CHUNKS";

    public static final String AZURE_EMBEDDING_SERVICE_ENDPOINT = "AZURE_EMBEDDING_SERVICE_ENDPOINT";
    public static final String AZURE_EMBEDDING_SERVICE_DEPLOYMENT_NAME = "AZURE_EMBEDDING_SERVICE_DEPLOYMENT_NAME";

    public static final String AZURE_SEARCH_SERVICE_ENDPOINT = "AZURE_SEARCH_SERVICE_ENDPOINT";
    public static final String AZURE_SEARCH_SERVICE_INDEX_NAME = "AZURE_SEARCH_SERVICE_INDEX_NAME";

    public static final String LLM_MODEL_RESPONSE_MAX_TOKENS = "LLM_MODEL_RESPONSE_MAX_TOKENS";
    public static final String LLM_MODEL_RESPONSE_VERBOSITY = "LLM_MODEL_RESPONSE_VERBOSITY";
    public static final String LLM_CHAT_SERVICE_PROVIDER = "LLM_CHAT_SERVICE_PROVIDER";
    public static final String MAX_DOCUMENT_UPLOAD_BLOB_SIZE_MIB = "MAX_DOCUMENT_UPLOAD_BLOB_SIZE_MIB";

    private SharedSystemVariables() {
        // Prevent instantiation
    }


}
