package uk.gov.moj.cp.retrieval.service;

import static uk.gov.moj.cp.ai.util.EnvVarUtil.getRequiredEnv;
import static uk.gov.moj.cp.ai.util.StringUtil.isNullOrEmpty;

import uk.gov.moj.cp.ai.model.ChunkedEntry;
import uk.gov.moj.cp.ai.service.ChatService;
import uk.gov.moj.cp.ai.util.ChunkFormatterUtility;
import uk.gov.moj.cp.ai.util.EnvVarUtil;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ResponseGenerationService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ResponseGenerationService.class);

    private final ChatService chatService;
    private final CitationProcessor citationProcessor;
    private final ChunkFormatterUtility chunkFormatterUtility;
    private final UserInstructionService userInstructionService;

    private final String systemPromptTemplate;

    public ResponseGenerationService() {
        String endpoint = getRequiredEnv("AZURE_OPENAI_ENDPOINT");
        String deploymentName = getRequiredEnv("AZURE_OPENAI_CHAT_DEPLOYMENT_NAME");

        // Using managed identity - pass null for API key to enable managed  identity
        chatService = new ChatService(endpoint, deploymentName);
        citationProcessor = new CitationProcessor();
        chunkFormatterUtility = new ChunkFormatterUtility();
        userInstructionService = new UserInstructionService();

        systemPromptTemplate = getRequiredEnv("RESPONSE_GENERATION_SYSTEM_PROMPT");
    }

    public ResponseGenerationService(final ChatService chatService, final CitationProcessor citationProcessor, final ChunkFormatterUtility chunkFormatterUtility, final UserInstructionService userInstructionService, final String systemPromptTemplate) {
        this.chatService = chatService;
        this.citationProcessor = citationProcessor;
        this.chunkFormatterUtility = chunkFormatterUtility;
        this.userInstructionService = userInstructionService;
        this.systemPromptTemplate = systemPromptTemplate;
    }

    public String generateResponse(final String userQuery, final List<ChunkedEntry> chunkedEntries, final String userQueryPrompt) {
        LOGGER.info("Generating LLM response for query: {}", userQuery);

        if (null == chunkedEntries || chunkedEntries.isEmpty()) {
            LOGGER.warn("No matching data from search database retrieved for query: {}", userQuery);
            return "No response generated by the service.";
        }

        final String formattedChunks = chunkFormatterUtility.buildChunkContext(chunkedEntries);
        LOGGER.info("Constructed retrieved contexts: \n{}", formattedChunks);
        final String userInstruction = userInstructionService.buildUserInstruction(userQuery, userQueryPrompt, formattedChunks);

        try {
            return chatService.callModel(systemPromptTemplate, userInstruction, String.class)
                    .filter(response -> !isNullOrEmpty(response))
                    .map(response -> {
                        String trimmedResponse = citationProcessor.processAndFormatCitations(response);
                        LOGGER.info("LLM Raw Response length = {}", trimmedResponse.length());
                        return trimmedResponse;
                    })
                    .orElseGet(() -> {
                        LOGGER.warn("LLM returned no response.");
                        return "No response generated by the service.";
                    });
        } catch (Exception e) {
            LOGGER.error("Error generating response for user query: {}", userQuery, e);
            return "An error occurred while generating the response.";
        }
    }
}