package uk.gov.moj.cp.retrieval.service;

import static uk.gov.hmcts.cp.openapi.model.AnswerGenerationStatus.ANSWER_GENERATED;
import static uk.gov.hmcts.cp.openapi.model.AnswerGenerationStatus.ANSWER_GENERATION_FAILED;
import static uk.gov.moj.cp.ai.util.EnvVarUtil.getRequiredEnv;
import static uk.gov.moj.cp.ai.util.StringUtil.isNullOrEmpty;
import static uk.gov.moj.cp.ai.util.StringUtil.unescapeContent;

import uk.gov.moj.cp.ai.client.ChatServiceFactory;
import uk.gov.moj.cp.ai.exception.ChatServiceException;
import uk.gov.moj.cp.ai.model.ChunkedEntry;
import uk.gov.moj.cp.ai.service.ChatService;
import uk.gov.moj.cp.ai.util.ChunkFormatterUtility;
import uk.gov.moj.cp.retrieval.exception.CitationDegradedException;
import uk.gov.moj.cp.retrieval.model.CitationGuardMode;
import uk.gov.moj.cp.retrieval.model.LlmResponse;
import uk.gov.moj.cp.retrieval.service.CitationProcessor.CitationOutcome;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ResponseGenerationService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ResponseGenerationService.class);

    static final String LLM_RESPONSE_NO_DATA_AVAILABLE = "No data available matching the query.";
    public static final String LLM_RESPONSE_FAILURE_TO_GENERATE = "No response generated by the service.";

    private final ChatService chatService;
    private final CitationProcessor citationProcessor;
    private final ChunkFormatterUtility chunkFormatterUtility;
    private final UserInstructionService userInstructionService;

    private final String systemPromptTemplate;
    private final CitationGuardMode guardMode;

    public ResponseGenerationService() {
        String endpoint = getRequiredEnv("AZURE_OPENAI_ENDPOINT");
        String deploymentName = getRequiredEnv("AZURE_OPENAI_CHAT_DEPLOYMENT_NAME");

        chatService = ChatServiceFactory.getInstance(endpoint, deploymentName);
        citationProcessor = new CitationProcessor();
        chunkFormatterUtility = new ChunkFormatterUtility();
        userInstructionService = new UserInstructionService();

        systemPromptTemplate = unescapeContent(getRequiredEnv("RESPONSE_GENERATION_SYSTEM_PROMPT"));
        guardMode = CitationGuardMode.fromEnv();
    }

    public ResponseGenerationService(final ChatService chatService, final CitationProcessor citationProcessor, final ChunkFormatterUtility chunkFormatterUtility, final UserInstructionService userInstructionService, final String systemPromptTemplate) {
        this(chatService, citationProcessor, chunkFormatterUtility, userInstructionService, systemPromptTemplate,
                CitationGuardMode.fromEnv());
    }

    ResponseGenerationService(final ChatService chatService, final CitationProcessor citationProcessor,
                              final ChunkFormatterUtility chunkFormatterUtility,
                              final UserInstructionService userInstructionService,
                              final String systemPromptTemplate,
                              final CitationGuardMode guardMode) {
        this.chatService = chatService;
        this.citationProcessor = citationProcessor;
        this.chunkFormatterUtility = chunkFormatterUtility;
        this.userInstructionService = userInstructionService;
        this.systemPromptTemplate = systemPromptTemplate;
        this.guardMode = guardMode;
    }

    /**
     * Generates the answer with a single LLM attempt. When the citation guard is active
     * ({@code CITATION_GUARD_MODE} != OFF) and the answer comes back citation-degraded, a
     * {@link CitationDegradedException} carrying the degraded answer is thrown — retry and
     * exhaustion policy belong to the caller: the async queue worker retries via queue
     * redelivery; the synchronous path applies the policy immediately.
     */
    public LlmResponse generateResponse(final String userQuery, final List<ChunkedEntry> chunkedEntries,
                                        final String userQueryPrompt) throws ChatServiceException {
        if (null == chunkedEntries || chunkedEntries.isEmpty()) {
            LOGGER.warn("No matching data from search database retrieved for query: {}", userQuery);
            return new LlmResponse(LLM_RESPONSE_NO_DATA_AVAILABLE, LLM_RESPONSE_NO_DATA_AVAILABLE, ANSWER_GENERATED);
        }

        LOGGER.info("Generating LLM response for query: {}", userQuery);

        final String formattedChunks = chunkFormatterUtility.buildChunkContext(chunkedEntries);
        LOGGER.info("Constructed retrieved contexts, has {} characters", formattedChunks.length());

        final String userInstruction = userInstructionService.buildUserInstruction(userQuery, userQueryPrompt, formattedChunks);

        return chatService.callModel(systemPromptTemplate, userInstruction, String.class)
                .filter(rawLlmResponse -> !isNullOrEmpty(rawLlmResponse))
                .map(this::toGuardedResponse)
                .orElseGet(() -> {
                    LOGGER.warn("LLM returned no response.");
                    return new LlmResponse(LLM_RESPONSE_FAILURE_TO_GENERATE, LLM_RESPONSE_FAILURE_TO_GENERATE, ANSWER_GENERATION_FAILED);
                });
    }

    /** Applies the citation guard to one raw answer; throws {@link CitationDegradedException} when degraded. */
    private LlmResponse toGuardedResponse(final String rawLlmResponse) {
        final CitationOutcome outcome = citationProcessor.processCitations(rawLlmResponse);
        if (isAcceptable(outcome)) {
            LOGGER.info("LLM Raw Response length = {}", outcome.formattedText().length());
            return new LlmResponse(rawLlmResponse, outcome.formattedText(), ANSWER_GENERATED);
        }
        final String reason = String.format(
                "Citations missing: jsonBlock=%s, inlineMarkers=%d, rendered=%d, stripped=%d",
                outcome.jsonBlockPresent(), outcome.inlineMarkers(),
                outcome.renderedCitations(), outcome.strippedMarkers());
        LOGGER.warn("Citation guard: degraded answer — {}.", reason);
        throw new CitationDegradedException(reason, rawLlmResponse, outcome.formattedText());
    }

    /**
     * An answer may progress when it carries at least one rendered citation, or when it is a
     * deliberate no-evidence refusal (block present, empty array, no markers written). With the
     * guard off every non-empty answer is accepted (pre-guard behaviour).
     */
    private boolean isAcceptable(final CitationOutcome outcome) {
        if (guardMode == CitationGuardMode.OFF) {
            return true;
        }
        if (outcome.renderedCitations() >= 1) {
            return true;
        }
        return outcome.jsonBlockPresent() && outcome.emptyFactMap() && outcome.inlineMarkers() == 0;
    }
}