package uk.gov.moj.cp.orchestrator;

public enum FunctionAppName {
    ANSWER_RETRIEVAL_FUNCTION,
    ANSWER_SCORING_FUNCTION,
    DOCUMENT_STATUS_CHECK_FUNCTION,
    DOCUMENT_METADATA_CHECK_FUNCTION,
    DOCUMENT_INGESTION_FUNCTION
}
